### ISSUE TITLE
Batch size is 1, what's the technical problem?

### ISSUE THREAD

**Issue by sjtuytc** [ehsanik/touchTorch#2]
It seems that you don't support batch_size > 1 currently, what's the problem? Did you try to use vec_env to run multiple environments parallelly?

**Comment by ehsanik** [comment]
We aggregate different batches every 64 steps (See [here](https://github.com/ehsanik/touchTorch/blob/master/solvers/train.py#L57)). We run multiple environments in parallel and each environment belongs to a specific object category. Therefore we load each object mesh once and just switch between environments.
