### ISSUE TITLE
Missing keys in gtforce_train.json

### ISSUE THREAD

**Issue by sjtuytc** [ehsanik/touchTorch#3]
Hi, when getting the gt force with the command

`python main.py --title save_gt_force --batch-size 1 --workers 10 --gpu-ids 1 --number_of_cp 5 --model NoModelGTForceBaseline --dataset BaselineForceDatasetWAugmentation --loss KeypointProjectionLoss --object_list ALL --break-batch 1 --data DatasetForce --predicted_cp_adr DatasetForce/gtforce_train.json savegtforce`

It reports multiple key errors. E.g. the following key does not appear to be in the json file. What's the problem?
2019-09-13 16:02:56.192963__2019-09-13 16:02:56.260085__2019-09-13 16:02:56.295750__2019-09-13 16:02:56.333490__2019-09-13 16:02:56.392591__2019-09-13 16:02:56.457906__2019-09-13 16:02:56.496180__2019-09-13 16:02:56.556228__2019-09-13 16:02:56.626922__2019-09-13 16:02:56.666089

**Comment by ehsanik** [comment]
As explained in the paper, we run direct force regression for toy airplane. The missing frames are for other objects. Feel free to use the code to obtain pseudo-groundtruth forces for other objects as well.
