### ISSUE TITLE
missing function get_rgb_for_position_rotation

### ISSUE THREAD

**Issue by sjtuytc** [ehsanik/touchTorch#4]
hi, thanks for your sharing code. In visualization_util.py, many functions require get_rgb_for_position_rotation. Would you mind releasing the implementation of this function? It would help others to work on your dataset and qualifying their results.  Thanks a lot!

**Comment by ehsanik** [comment]
This function simply just transforms the location and orientation of the object to the specified position and rotation and gets the rgb image from PyBullet using `getCameraImage` function.
